ddsc/uploadtool.py

Relative "../test" and absolute "/tmp/jpb" paths for folder appear to work now.

Fix for Relative paths do not work. #1

---

ddsc/__main__.py
ddsc/ddsapi.py
ddsc/ddsclient.py
ddsc/localstore.py
ddsc/remotestore.py
ddsc/tests/test_localstore.py
ddsc/tests/test_remotestore.py
ddsc/util.py

Changed the code to rely on the file hash when determining to re upload a file(create a duplicate currently). Commented methods better to allow easier reading. Added command line arguments for adding user permissions on dds. Experimental support for symbolic links.  Also other little fixes.

Checking hash, public method params commented, add user permissions.

---

README.md

Adds the status badge to the README

Include travis badge in README

---

.gitignore
.travis.yml
ddsc/__main__.py
ddsc/cmdparser.py
ddsc/ddsclient.py
ddsc/localstore.py
ddsc/remotestore.py

Added future print function.
Fixed difference between 2 and 3 when no arguments passed.
Fixed imports for 3.
Added code to have a better progress bar #15.
Travis changes to test python2.7 and python3 .

support python 3.5 and better progress bar

---

ddsc/localstore.py

Fix off by one bug in chunk count for progress bar

---

ddsc/cmdparser.py
ddsc/ddsclient.py
ddsc/localstore.py

Looks like python 3.5 supports unicode with no changes.
These changes are just for 2.7.

unicode support for 2.7

---

README.md
ddsc/cmdparser.py
ddsc/ddsapi.py
ddsc/ddsclient.py
ddsc/remotestore.py
ddsc/tests/test_localstore.py
ddsc/tests/test_remotestore.py
integration_test.sh

Support for -user and -email in ddsclient add_user command.
Fix deprecated warnings when running tests with python3.
integration_test.sh - uploads source code and must be visually checked via web portal

Add by email

---

ddsc/cmdparser.py
integration_test.sh

Use - for small and -- for long parameters.
Add missing description for add_user command.

Cleanup dashes

---

README.md
ddsc/ddsclient.py

Added a blurb to the README and fixed a confusing variable name.
Fixes #36

fixing docs and confusing variable name

---

ddsc/core/ddsapi.py
ddsc/core/remotestore.py

ddsapi method get_user_by_id  GETs a user from the /users/{id} endpoint
remotestore method fetch_user populates above into a RemoteUser object

Adds get_user_by_id and fetch_user

---

ddsc/core/handover.py
setup.py

Changed url endpoints to match handover service.
Fixed bad parameter names.
Include message from request in errors.

Fixes to work with DukeDSHandoverService.

---

api_test.py
ddsc/cmdparser.py
ddsc/config.py
ddsc/core/ddsapi.py
ddsc/core/handover.py
ddsc/ddsclient.py
requirements.txt
setup.py

Additional handover changes and api_test script.

Mail draft

---

ddsc/core/filedownloader.py
ddsc/core/fileuploader.py
ddsc/core/tests/test_fileuploader.py
setup.py

Fixes #60 
@dleehr could you review?

Zero byte file

---

ddsc/core/ddsapi.py
ddsc/core/fileuploader.py
ddsc/core/localstore.py
ddsc/core/parallel.py
ddsc/core/projectuploader.py
ddsc/core/remotestore.py
ddsc/core/tests/test_fileuploader.py
ddsc/core/tests/test_parallel.py
ddsc/core/tests/test_projectuploader.py
ddsc/core/tests/test_remotestore.py
ddsc/core/upload.py

**High level changes**
For small items upload them in parallel.
For large files upload them one at a time but upload the chunks in parallel.
Use a http session in background workers.
**Generic Parallel Functionality** 
`ddsc/core/parallel.py` contains generic classes for running functions in parallel.
This allows a user to build up a series of dependent parallel tasks.
TaskRunner executes a list of Tasks in parallel based on how many processes can be run at once.
Each Task consists of a unique_id, an task_id that it will wait for before running and a Command to execute. Each Command contains a function pointer to a global function to be run in the background and some setup/cleanup methods that will be run in the foreground.
**Project Uploader**
`ddsc/core/projectuploader.py` creates a …

Speeds uploading many files.

---

.travis.yml
README.md

Runs code coverage as part of travis-ci. Sends results to coveralls.io.
Code coverage details: https://coveralls.io/github/Duke-GCB/DukeDSClientcoveralls.io
Badge added to README

Code Coverage

---

.travis.yml

Trying out travis setup to automate pypi deployment on new releases.

Setup pypi automatic dist on new releases

---

ddsc/ddsclient.py
setup.py

Display messages after prompting for msg-file

---

ddsc/ddsclient.py

no longer fetching project children as part of delete command
Fixes #138

faster delete command

---

ddsc/core/filedownloader.py
ddsc/core/tests/test_filedownloader.py

Adds code to retry downloading a chunk if it fails.
Retries for both connection errors and partial data being received.
Fixes #151

Retry downloading chunks

---

ddsc/cmdparser.py
ddsc/ddsclient.py
ddsc/tests/test_cmdparser.py

Add description with version to help

---

ddsc/core/localstore.py
ddsc/core/tests/test_fileuploader.py
ddsc/core/tests/test_localstore.py

Fix ignore dir bug

---

ddsc/core/ddsapi.py
ddsc/core/tests/test_ddsapi.py

Will be using this API in D4S2

Adds ddsapi.get_all_project_transfers to list all known transfers

---

README.md

gemnasium has been closed
https://docs.gitlab.com/ee/user/project/import/gemnasium.html

remove gemnasium badge

---

.circleci/config.yml
deploy/onpublish.py
deploy/onpublish.sh

updates scripts to be circleci specific
adds command to circle after deploying to pypi

Call onpublish.sh from CircleCI

---

ddsc/sdk/client.py
ddsc/sdk/dukeds.py
ddsc/sdk/tests/test_client.py
ddsc/sdk/tests/test_dukeds.py

Fix bug where importing DukeDS read config file

---

ddsc/core/ddsapi.py
ddsc/core/tests/test_ddsapi.py

Adds logic to retry ReadTimeout exceptions for GET and PUT DukeDS API requests.
Fixes #266

Retry ReadTimeout errors

---

deploy/ddsclient-generic-gcb01.spec

Upgrades spec file to python 3.6

upgrade ddsclient spec file to Anaconda3/5.0.1

---

ddsc/core/download.py
ddsc/core/tests/test_download.py

Adds messages explaining to user details about files being considered for downloading and number of local files that are already up to date. This change adds `Checking ...` and `Verified ...` lines to the output during the download process.
Example command line output for downloading a project where 3 files have already been downloaded successfully:
```
$ download -p testproject
Fetching list of files/folders.
Checking 11 files.
Verified 3 local files are already up to date.
Downloading 8 files.
Done: 100%             <- progresss bar was here                             
Verifying contents of 8 downloaded files using file hashes.
testproject/docs/images/OSXTerminalSetting.png e249748630632d26422d272789cc021b md5 OK
...
All downloaded files have been verified successfully.
```
Fixes #281

improve messaging during downloading

---

ddsc/core/ddsapi.py
ddsc/core/fileuploader.py
ddsc/core/tests/test_fileuploader.py

Change to prevent problem identified in #292

verify uploads before completing them

---

ddsc/core/download.py
ddsc/core/fileuploader.py
ddsc/core/projectuploader.py
ddsc/core/tests/test_projectuploader.py
ddsc/core/tests/test_util.py
ddsc/core/util.py

Adds speed to upload progress bar.
Fixes #302

Show speed in upload progress

---

DukeDS/__init__.py
ddsc/sdk/client.py
ddsc/sdk/dukeds.py
ddsc/sdk/tests/test_client.py
ddsc/sdk/tests/test_dukeds.py

add sdk create_folder function

---

ddsc/core/download.py
ddsc/core/tests/test_download.py

Fixes downloading for python2

---

README.md
ddsc/core/util.py

improve documentation for users new to the command line

---

ddsc/azure.py
ddsc/cmdparser.py
ddsc/config.py
ddsc/core/util.py
ddsc/ddsclient.py
ddsc/sdk/azure.py

Adds --azure command line flag. Also adds .ddsclient `backing_storage` config option that can be "dds" or "azure". 
Adds placeholders for various azure ddsclient commands with dummy azure project/file data.
Fixes #332

Add options to configure azure mode

---

ddsc/azure/__main__.py
ddsc/azure/api.py
ddsc/azure/commands.py
ddsc/azure/delivery.py
ddsc/azure/tests/test_azure_api.py
ddsc/azure/tests/test_delivery.py
ddsc/cmdparser.py
ddsc/config.py
ddsc/ddsclient.py
ddsc/tests/test_config.py
setup.py

The `ddd` command line tool has the same commands as `ddsclient`, but with some items unsupported (currently).

Add ddd command line tool for Cloud Storage

---

README.md
setup.py

Update README with python 3.7 dependency
The azure libraries do not support python 3.6.
Pin to working msgraph-core

Update README replacing ddsclient with ddd
