ddsc/core/ddsapi.py, ddsc/core/remotestore.py, setup.py
These are used by the handover service to get project details from DukeDS
a `fetch_remote_project` method already existed that took a project name as an argument, so this change set adds `fetch_remote_project_by_id`
=> Adds methods to get/fetch project by id

README.md, ddsc/config.py, ddsc/core/remotestore.py, ddsc/core/tests/test_remotestore.py, ddsc/tests/test_config.py, setup.py
Changes to support old and new versions of duke-data-service GET /api/v1/files/{id} payload.
Changed upload workers to default to the num CPUs.
=> duke-data-service GET files payload change

.gitignore, ddsc/config.py, ddsc/core/download.py, ddsc/core/filedownloader.py, ddsc/core/fileuploader.py, ddsc/core/remotestore.py, ddsc/core/tests/test_filedownloader.py, ddsc/core/util.py, ddsc/tests/test_config.py, setup.py, test_scripts/inside_docker.sh, test_scripts/run.sh
Changes download to use multiple processes similar to how upload works.
Added a `download_workers` config option to set how many processes to use.
We create a file to hold the parts by opening, seeking, writing(0).
Then create separate processes to download chunks and write to their part of the file.
We use the range header to download just the parts we need in each worker.
Using this method rather than separate files/merge due to performance differences.
The default setting for download_workers is number_cpu / 2. This seems to be optimum for the different places I tried this out.
Ran integration testing and did some manual testing.
Verified that we were spawning separate processes and after download checked file sizes/cksum/md5.
=> Parallel Download

ddsc/core/handover.py
Switching from `project_viewer` to `file_downloader`.
Project viewer can only see filenames and sizes so it wouldn't be useful for evaluating a draft project.
=> file_downloader for mail_draft

ddsc/config.py, ddsc/core/localstore.py, ddsc/core/tests/test_localstore.py, ddsc/core/upload.py, test_scripts/.hidden_file
adding file_exclude_regex to allow customization of which files are uploaded
it is currently set to a default regex that will exclude .DS_Store, .ddsclient and ._*
=> skip un-necessary hidden files when uploading

ddsc/cmdparser.py, ddsc/core/download.py, ddsc/core/handover.py, ddsc/core/pathfilter.py, ddsc/core/remotestore.py, ddsc/core/tests/test_pathfilter.py, ddsc/core/tests/test_remotestore.py, ddsc/core/util.py, ddsc/ddsclient.py
Adds two new mutually exclusive parameters to download and handover commands.
Adds remote_path to RemoteProject, RemoteFolder, and RemoteItem to simplify checking paths.
Created PathFilter to hold values from `--include` or `--exclude` and determine if a file should be added to download/handover.
Created PathFilteredProject which applies PathFilter to ProjectWalker via new FilteredProject class.
Fixes #73.
=> Adding --include PATH and --exclude PATH to download and handover

ddsc/cmdparser.py, ddsc/core/ddsapi.py, ddsc/core/remotestore.py, ddsc/core/tests/test_remotestore.py, ddsc/ddsclient.py
Adding `list_auth_roles` to ddsclient to display the current project level auth_roles from DukeDS.
This will allow a user to determine which values are valid for the `--auth_role` argument to the`add_user` command.
Usage: 
```ddsclient list_auth_roles```
Current Output:
```
project_admin - Can update project details, delete project, manage project level permissions and perform all file operations
project_viewer - Can only view project and file meta-data
file_downloader - Can download files
file_editor - Can view download create update and delete files
file_uploader - Can update files
```
Fixes #69.
=> Add list_auth_roles command to view project permission types

ddsc/cmdparser.py, ddsc/core/remotestore.py, ddsc/ddsclient.py, integration_test.sh
Fixes #77
Adds `remove_user` command.
Functionality was already there from previous changes just added a command line option to use it.
Improves how long `add_user` takes by not downloading all the metadata for folders and files.
This data is not necessary for `add_user` or `remove_user`.
=> remove_user command

api_test.py, ddsc/core/ddsapi.py, ddsc/core/remotestore.py, ddsc/core/tests/test_remotestore.py
**GOAL** 
Speed up how long it takes to retrieve the metadata about folders and files for a remote project.
When re-uploading a project with few file changes but containing many files/folders takes quite a while fetching remote folder/file metadata. This also effects downloading.
**SOLUTION**
Use DukeDS API recursive children option for a project.
This works via a unique feature of their API where specifying contains='' for children endpoints triggers a recursive search mode. More details here: https://github.com/Duke-Translational-Bioinformatics/duke-data-service/issues/671.
**CHANGES** 
Created RemoteProjectChildren class to parse list of files found in recursive project listing and create RemoteFiles/RemoteFolders. This works by iterating the list of files/folders looking for items …
=> Fast proj api

ddsc/core/d4s2.py
When we receive unauthorized status(401) back from D4S2 show instructions on how to get setup.
Message printed looks like this:
```
$ ddsclient share -p tar_100 --user dcl9
ERROR: Your account does not have authorization for D4S2 (the deliver/share service).
Please send an email to gcb-help@duke.edu titled 'D4S2 setup' so we can work with you to setup your account.
```
=> send user to gcb-help when not setup for share/deliver

ddsc/core/ddsapi.py, ddsc/core/fileuploader.py
Sending the file hash twice now.
Once in the initial creation of the upload(so it will work in production).
The second time when completing the upload(so it will work in uatest/dev).
Tested uploading docs to a project in both production and uatest.
Ran integration_test.sh for both production and uatest.
All succeeded.
=> backwards compatible api file upload has fix

ddsc/core/ddsapi.py
Adds methods on DataServiceAp for project transfer endpointsi:
- get_project_transfers
- get_project_transfer
- create_project_transfer
- accept_project_transfer
- reject_project_transfer
- cancel_project_transfer
Tested all against apidev.dataservice.duke.edu on December 2, 2016. Working as expected.
=> Adds methods to interact with project_transfer APIs

ddsc/config.py, ddsc/tests/test_config.py
Default upload and download workers will max out at 8.
Fixes #96.
=> limit upload/download workers to 8 workers

ddsc/core/ddsapi.py
starting simple here just to figure out the best way to integrate. I'm particularly interested in your thoughts for update_activity. My intent was to allow the same type of input that the api allows (i.e. can send a PUT without any real data). This isn't really something that requests supports (http://docs.python-requests.org/en/master/user/quickstart/). `Note that any dictionary key whose value is None will not be added to the URL's query string.`, so I threw a ValueError?
=> adding all activity calls to ddsc.core.ddsapi.py

ddsc/core/ddsapi.py, ddsc/core/tests/test_ddsapi.py, ddsc/versioncheck.py
Sends  `User-Agent: DukeDSClient/<version>` in header for requests to DukeDS API.
This will help tracking down versions that have breaking API changes.
=> Adds User agent to header

README.md, requirements.txt
Added DukeDSClient to Gemnasium to monitor required dependencies for vulnerabilities.
URL: https://gemnasium.com/github.com/Duke-GCB/DukeDSClient/
Gemnasium sends out emails when a dependency has a vulerability so we will know to upgrade.
Added the badge to the README.
Updated the dependencies to the latest version.
=> Gemnasium monitoring for modules

ddsc/cmdparser.py, ddsc/core/tests/test_util.py, ddsc/core/util.py
Changes in python3.6 on windows modify the way the PYTHONIOENCODING works.
There are three different flags introduced for IOENCODING now and the PYTHONIOENCODING value is no longer returned for stdout.encoding.
The returned value seems is always lowercase "utf-8".
Now we ignore case when checking the encoding for UTF.
Fixes #112
=> Allow for lowercase utf in encoding check

ddsc/__main__.py, ddsc/cmdparser.py, ddsc/config.py, ddsc/core/util.py, ddsc/ddsclient.py, ddsc/tests/test_config.py, ddsc/tests/test_util.py
Check ~/.ddsclient config file permissions and make sure it isn't readable by other users.
This is similar to how ssh tries to keep your keys safe.
Fixes #111
=> Check config perm

ddsc/core/ddsapi.py, ddsc/core/remotestore.py, ddsc/core/tests/test_ddsapi.py, ddsc/core/tests/test_remotestore.py, ddsc/ddsclient.py
There is a new api endpoint for registering user with DukeDS.
[POST /api/v1/auth_providers/{id}/affiliates/{uid}/dds_user](https://api.dataservice.duke.edu/apiexplorer#!/auth_providers/postApiV1AuthProvidersIdAffiliatesUidDdsUser)
This will allow sending projects to users who have not logged into dataservice.duke.edu yet.
This endpoint only works for netid so we can only make use of this when the `--user <netid>` flag is used. Keep in mind that this is only for users that already have a netid.
Changes were made to the following commands to autoregister:
- share
- deliver
- add_user
- remove_user
Fixes #115 
When autoregistering by email is available we will open a new issue to implement those changes.
=> Autoregister users when possible

ddsc/core/ddsapi.py, ddsc/core/tests/test_ddsapi.py
I think this was the result of a merge that worked but didn't make sense.
These two methods were using the older _get_all_pages method instead of _get_collection.
=> Fix list_auth_roles and get_project_transfers

ddsc/cmdparser.py
Replaces '_' with '-' for argument parsing.
=> Dashes instead of Underscores in command line

ddsc/cmdparser.py, ddsc/tests/test_cmdparser.py
Remove `add_user` and `remove_user` from help screens.
Fixes #123
=> Remove legacy options from help

ddsc/core/fileuploader.py, ddsc/core/tests/test_fileuploader.py
This is a fix to the upload_async method uploads chunks of a file in a background process.
When this method has an exception it will now send the error message back to the main process.
The main process already has code to cleanup processes and notify the user when this happens.
This is just to cleanup processes when an error occurs when talking to DukeDS-API or the Swift store. Before this change the user would have to hit Ctrl-C to terminate the process.
Also adds a sleep and retry on connection error when uploading a chunk via PUT.
=> Cleanup processes on error in parallel chunk uploading

ddsc/core/localstore.py, ddsc/core/tests/test_localstore.py, ddsc/core/tests/test_upload.py
When only an empty file needed to be uploaded we were not uploading it.
The code that calculates the progress bar/chunks returned 0 for the empty file.
DukeDS requires an empty chunk to be uploaded.
Changes here return 1 chunk for empty files.
Fixes #130
This only occurred when there was only an empty file changed.
=> Fix not uploading empty file

ddsc/core/ddsapi.py, ddsc/core/fileuploader.py, ddsc/core/projectuploader.py, ddsc/core/tests/test_ddsapi.py, ddsc/core/tests/test_fileuploader.py, integration_test.sh
Recreate requests session when we are retrying to send a chunk to the external host(swift currently). Also retries 5 times and waits 1 second between each retry.
Also fixes a bug in the integration_test script.
=> Recreate session before retrying external PUT

ddsc/core/ddsapi.py, ddsc/core/tests/test_ddsapi.py
For some api endpoints (project list in particular) we were sending the data
in the json payload. Switching to always sending paging data via query string.
Users with > 100 projects were seeing the project list duplicated from the command line.
Also caused issues where projects > 100 would end up duplicated.
Partially Fixes #143 (does not address the 500 error)
=> Always send paging data in query string

ddsc/__main__.py, ddsc/core/ddsapi.py, ddsc/core/fileuploader.py, ddsc/core/parallel.py, ddsc/core/projectuploader.py, ddsc/core/tests/test_ddsapi.py, ddsc/core/tests/test_fileuploader.py, ddsc/core/tests/test_parallel.py, ddsc/core/tests/test_projectuploader.py, ddsc/core/tests/test_util.py, ddsc/core/util.py
There are forth-coming changes to DukeDS related to [eventual consistency](https://github.com/Duke-Translational-Bioinformatics/duke-data-service/blob/develop/api_design/DDS-872-eventual_consistency_status.md).
DukeDS endpoints with new failures cases:
- __POST /projects/{id}/uploads__ - creates an upload so we can upload chunks of a file
- returns 404 with JSON data containing "code": "resource_not_consistent"
- __GET /files/{id}/url__ - get a url so we can download a file
- returns 400 - "reason": "reported chunk hash/size does not match that computed by StorageProvider"
- __GET /file_versions/{id)/url__ - get a url of a file version so we can download a file
- returns 400 - "reason": "reported chunk hash/size does not match that computed by 
There isn't anything we can do for the two …
=> Project upload eventual consistency changes

ddsc/config.py, ddsc/core/ddsapi.py, ddsc/core/tests/test_ddsapi.py, ddsc/tests/test_config.py
Fixes #145
Changes error messages to determine the actual config filename used.
The config filename defaults to `~/.ddsclient` but is overridable via the `DDSCLIENT_CONF` environment variable: https://github.com/Duke-GCB/DukeDSClient/wiki/Configuration
=> Show actual config filename in errors

.travis.yml, deploy/onpublish.py
By default travis deploys once for every python version.
Changes here only deploy using the 3.5 deploy.
The pypi deploy seems ok with being run twice.
This caused deploying to the Duke-GCB/helmod repo twice.
Also fixed the helmod deploy script to be python 3.5 compatible.
=> Prevent duplicate deploys

ddsc/cmdparser.py, ddsc/core/remotestore.py, ddsc/core/tests/test_remotestore.py, ddsc/ddsclient.py, ddsc/tests/test_cmdparser.py, ddsc/tests/test_ddsclient.py
Adds `--auth-role <auth-role>` argument to the `list` command.
This option is mutually exclusive with the -p <project_name> argument.
Fixes #150
=> Allow filtering project list by auth role

ddsc/core/ddsapi.py, ddsc/core/download.py, ddsc/core/fileuploader.py, ddsc/core/projectuploader.py, ddsc/core/tests/test_ddsapi.py, ddsc/core/tests/test_fileuploader.py, ddsc/core/tests/test_util.py, ddsc/core/util.py
When downloading a file there is a special 404 that has a `resource_not_consistent` value in `code`. This occurs when the file url is not currently ready. A background DukeDS process should finish up with the file and we can try again.  Similar to what we did with uploads waiting for the project to get ready we will pause and retry. The user will see a message that we are waiting.
Fixes #152
=> Retry inconsistent downloads

ddsc/core/tests/test_util.py, ddsc/core/util.py
When ddsclient output was piped or redirected to a file
the terminal encoding error was raised. We will now allow
None as an encoding value.
Fixes #154
=> Allow empty/none for terminal encoding

README.md
Github markdown rendering requires there to be whitespace between heading text and heading level marker.
=> Inserts missing whitespace before heading text

ddsc/cmdparser.py, ddsc/core/d4s2.py, ddsc/core/download.py, ddsc/core/projectuploader.py, ddsc/core/remotestore.py, ddsc/core/tests/test_d4s2.py, ddsc/core/tests/test_download.py, ddsc/core/tests/test_projectuploader.py, ddsc/core/tests/test_remotestore.py, ddsc/core/tests/test_upload.py, ddsc/core/upload.py, ddsc/core/util.py, ddsc/ddsclient.py, ddsc/tests/test_cmdparser.py, ddsc/tests/test_ddsclient.py, ddsc/tests/test_util.py
Changes to allow selecting project via `-i` argument flag. This option is mutually exclusive from the -p flag which selects project by project name. This also adds a long option(`-l`) to the list command to allow user to find the id's associated with projects.
=> Project id flag

ddsc/core/download.py, ddsc/core/filedownloader.py, ddsc/core/tests/test_filedownloader.py, ddsc/core/util.py
Moves code that fetches the url into the background process that downloads the chunk. That way we use it immediately after we retrieve it. Otherwise there is a possibility that we end up trying to download an expired url. This scenario was likely when retrying downloads due to connection problems. When we must retry downloading part of a file due to a connection error it will re-fetch the url.
Fixes #165
=> Fix for 401 error when downloading part of a file

ddsc/config.py, ddsc/core/ddsapi.py, ddsc/core/tests/test_ddsapi.py, ddsc/ddsclient.py, ddsc/tests/test_config.py
Allows users to customize the page size used when fetching paginated data from DukeDS.
Lowering this value from the default of 100 may help with 500 errors due to timeouts and paginated data.
Also displays a message before and after we download the list of files in a project.
This will let users know ddsclient isn't hung when this request takes a while.
=> Configurable page size and fetch file list message

.travis.yml
2.7 was the version that was tested against
using 3.5 inside travis seems to have some issue talking to github
=> use python 2.7 for deploy/onpublish.py

ddsc/core/ignorefile.py, ddsc/core/localstore.py, ddsc/core/tests/test_ignorefile.py, ddsc/core/tests/test_localstore.py
Using this library to allow more natural command line wildcards: https://docs.python.org/2/library/fnmatch.html
Supports `.ddignore` files inside directories that are uploaded.
=> upload reads unix-shell wildcards from .ddsignore in folders

ddsc/core/ddsapi.py, ddsc/core/tests/test_ddsapi.py
Retry DukeDS API requests while the service is down for maintenance (ie returns 503).
Waits a minute between retries.
Displays a message when it starts waiting.
=> Retry requests when DukeDS service is down for maintenance

ddsc/cmdparser.py, ddsc/core/d4s2.py, ddsc/core/tests/test_d4s2.py, ddsc/ddsclient.py, ddsc/tests/test_cmdparser.py, ddsc/tests/test_ddsclient.py
Adds two new flags to the `deliver` command to specify a list of users to have a project shared with once the delivery is accepted by the owner.
Requires https://github.com/Duke-GCB/D4S2/pull/102
=> Deliver share users

ddsc/cmdparser.py, ddsc/core/download.py, ddsc/core/tests/test_download.py, ddsc/core/util.py, ddsc/ddsclient.py, ddsc/tests/test_cmdparser.py, ddsc/tests/test_ddsclient.py
Option to allow a user to resume a download by adding `--resume` or `-r` to the `download` command. Without this flag if the destination directory contains files/folders the download command will stop. This flag will allow the download command to continue.  Additionally we  will skips downloading files that already exist and have the same hash as the remote file.
=> Resume download

ddsc/core/filedownloader.py
A user downloading a large project (large files and many files) received an error like this:
```
...SSLError(IOError(24, Too many open files...
```
Changes here fix a file handle leak that caused this problem.
Fixes #188
=> Fix file handle leak

ddsc/core/d4s2.py, ddsc/core/tests/test_d4s2.py
Raises exception if trying to run share or deliver command
to a user that doesn't have an email. Obviously this will only
be a problem when user the --user <userid> option.
Fixes #191
=> Prevent share or delivery to user with no email

ddsc/core/d4s2.py, ddsc/core/tests/test_d4s2.py
Still allows users to specify sharing with themselves when delivering.
This is just limiting who we can transfer ownership to.
=> Prevent sharing/delivering with self

ddsc/core/remotestore.py, ddsc/core/tests/test_remotestore.py
In support of https://github.com/Duke-GCB/D4S2/issues/162, adds fields to the RemoteUser class, to avoid fetching these separately.
=> Adds first_name, last_name to RemoteUser

ddsc/core/ddsapi.py, ddsc/core/tests/test_ddsapi.py
Adds get_project_permissions to DataServiceApi.
For use by https://github.com/Duke-GCB/D4S2/pull/170
=> api: add ability to list project permissions

ddsc/core/tests/test_upload.py, ddsc/core/upload.py
When a project is uploaded the url to the portal is printed out to the command line.
The url displayed on the command line resulted in a 404.
Removes `portal/` from the url to match the updated DukeDS website.
Fixes #206
=> fix portal url

ddsc/cmdparser.py, ddsc/core/download.py, ddsc/core/tests/test_download.py, ddsc/ddsclient.py, ddsc/tests/test_cmdparser.py, ddsc/tests/test_ddsclient.py
Currently the `deliver` command defaults to delivering a copy of a project.
Changes here will default `deliver` to delivering the project specified.
The `--skip-copy` flag has been removed.
There is a new `--copy` flag that a user can specify to deliver a copy of the project.
Fixes #180 
In making these changes found an error for running `ddsclient` with a copy command.
The method was missing a parameter.
Fixes #205
=> default to delivering project instead of a copy

ddsc/core/ddsapi.py, ddsc/core/localstore.py, ddsc/core/remotestore.py, ddsc/core/tests/test_ddsapi.py, ddsc/core/tests/test_localstore.py, ddsc/core/tests/test_remotestore.py
Speeds up finding users by username(netid) or email by using the new filtering options available at DukeDS API [users/ endpoint](https://api.dataservice.duke.edu/apiexplorer#!/users/getApiV1Users).
Also adds `get_auth_provider_affiliates` to `DataServiceApi` in case we need to use this in the future.
Fixes #209
=> Make use of new DukeDS API user filtering by email and username

ddsc/core/tests/test_localstore.py
Using comparison against a file listing structure instead of the strange nested string comparisions.
Fixes #211
=> streamline localstore tests

ddsc/core/download.py, ddsc/core/tests/test_download.py
Resets actual_bytes_read before trying/retrying download files.
On a retry _verify_download_complete will not erronously fail.
Fixes #214
=> download too few bytes retrying fix

ddsc/core/ddsapi.py, ddsc/core/tests/test_ddsapi.py
Implemented in DDS via https://github.com/Duke-Translational-Bioinformatics/duke-data-service/pull/1250 and needed by https://github.com/Duke-GCB/D4S2/issues/107
=> Update get_auth_provider_affiliates to query on username and email

requirements.txt, setup.py
This is to fix a vulnerability found by github:
```
Remediation
Upgrade requests to version 2.20.0 or later. For example:
requests>=2.20.0
Always verify the validity and compatibility of suggestions with your codebase.
Details
CVE-2018-18074 More information
moderate severity
Vulnerable versions: <= 2.19.1
Patched version: 2.20.0
The Requests package through 2.19.1 before 2018-09-14 for Python sends an HTTP Authorization header to an http URI upon receiving a same-hostname https-to-http redirect, which makes it easier for remote attackers to discover credentials by sniffing the network.
```
Requests uses [semantic versioning](http://docs.python-requests.org/en/master/dev/philosophy/#semantic-versioning). 
Integration test passed running against DukeDS dev server.
Fixes #218
=> update requests requirement

deploy/onpublish.py
Fixes #223 
The call to str() resulted in a string starting with `b'`.
Fixes here to properly encode the helmod module specfile.
The other issue here was an incorrectly configured github token. 
The token needs the repo scope permissions.
=> fix python3 encoding for publishing helmod module

ddsc/config.py, ddsc/core/ddsapi.py, ddsc/core/fileuploader.py, ddsc/core/projectuploader.py, ddsc/core/tests/test_ddsapi.py, ddsc/core/tests/test_fileuploader.py, ddsc/core/tests/test_projectuploader.py, ddsc/sdk/client.py, ddsc/sdk/tests/test_client.py, ddsc/tests/test_config.py
Adds config file setting `storage_provider_id` to specify a particular storage provider id.
This storage provider id is specified when creating a file upload 
[POST /api/v1/projects/{project_id}/uploads](https://apiuatest.dataservice.duke.edu/apiexplorer#!/projects/postApiV1ProjectsProjectIdUploads)
This is not intended to be used by end users but just for developers testing various DukeDS backends.
Adds retry around create upload URL requests. 
Previously this never failed with the 404 with a retry hint but does so with the new provider.
Adds change to send chunk numbers > 0. The swift DukeDS backend supported 0 based chunk indexing, however the S3 DukeDS backend does not. For multi part files we sent chunk indexes starting with index 0 since this is easier to reason about related to the …
=> changes to support s3 provider

ddsc/core/download.py, ddsc/core/tests/test_download.py
Handles two more differences when working against the new DukeDS S3 backend.
Previously DukeDSClient added a `/` between the `host` and `url` fields that needed to be combined to download a file. We stop doing so due to this causing errors in S3.
Another issue is retrying expired urls.
Swift returns 401 status code when a url is expired.
S3 returns a 403 status code when a url is expired.
Fixes #229
=> Fix 403 S3 errors when downloading

ddsc/config.py, requirements.txt, setup.py
Changes pyyaml to >= 5.1 in setup.py to resolve https://nvd.nist.gov/vuln/detail/CVE-2017-18342.
Fixes warning for new installations of DukeDSClient that pull in pyyaml 5.1:
```
/Users/jpb67/Documents/work/DukeDSClient/ddsc/config.py:86: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
self.update_properties(yaml.load(yaml_file))
```
=> upgrade pyyaml requirement to 5.1

ddsc/core/ddsapi.py, ddsc/core/fileuploader.py, ddsc/core/projectuploader.py, ddsc/core/tests/test_ddsapi.py, ddsc/core/tests/test_fileuploader.py, ddsc/core/tests/test_projectuploader.py
When uploading a single chunk file use the new DukeDS api feature to upload non-chunked upload.
This avoids one request to DukeDS and simplifies the background processing when they create files in the backend stores. 
As a byproduct of using the chunked option this change fixes S3 uploads of empty files.
Fixes #231
=> Improve small file uploads

ddsc/core/download.py, ddsc/core/remotestore.py, ddsc/core/tests/test_download.py, ddsc/ddsclient.py, ddsc/sdk/client.py, ddsc/sdk/tests/test_client.py, ddsc/tests/test_ddsclient.py
Changes downloading to verify the contents of files downloaded. This is done by calculating an MD5 sum for each file and comparing it against the value provided by DukeDS.
Also prints messages informing the user about progress download and checking files.
Example successful download messaging:
```
Fetching list of files/folders.
Downloading 1 files.
Done: 100%                         <- this line is where the download progress bar displays                         
Verifying contents of 1 downloaded files using file hashes.
All downloaded files have been verified successfully.
```
Fixes #240
=> When downloading files validate their checksums

ddsc/core/util.py, ddsc/tests/test_util.py
Implements showing file's hash value requested in #228.
When a project contents are listed with long option like so:
```
ddsclient list -p <projectName> -l
```
Example output:
```
b10fe5b7-5021-4094-a687-f6442411d4ab - Project <projectName> Contents:
1f0e2240-892b-4a12-bb16-b6165c923b52	requirements.txt	(md5:8d3e8765edb0c97bb59c43c93864e36d)
d38b28d8-1e12-410a-99ae-d4e8f8715494	mushroom.svg	(md5:803283746359c515be00450aa3b16da6)
```
=> Displays file hash when listing project with long option

ddsc/core/download.py, ddsc/core/remotestore.py, ddsc/core/tests/test_download.py, ddsc/core/tests/test_remotestore.py, ddsc/core/util.py, ddsc/sdk/client.py, ddsc/sdk/tests/test_client.py
Changes download methods to let user specify path to download a file to.
Renames `FileUrlDownloader` to `FileDownloader` and requires a new class called `FileToDownload` that specifies both the data required to download and a path to download the file into. Renames some no longer accurate variable names.
Improves the performance of the `DukeDS.download_file(<project>, <remote_path>, <local_path>)`.
This is accomplished by changing [File.download_to_path](https://github.com/Duke-GCB/DukeDSClient/blob/e8d16e4aae8d854235d413becf8551e7bd60a645/ddsc/sdk/client.py#L383) to download large files in parallel by using `FileDownloader`.
Fixes [bug in hash checking](https://github.com/Duke-GCB/DukeDSClient/blob/a13f4da745c041ecfa9b9fb5ea830cb60f15ede9/ddsc/sdk/client.py#L399) that was using the wrong …
=> Faster sdk download

DukeDS/__init__.py, ddsc/core/ddsapi.py, ddsc/core/ddsuserutil.py, ddsc/core/remotestore.py, ddsc/core/tests/test_ddsapi.py, ddsc/core/tests/test_remotestore.py, ddsc/core/tests/test_userutil.py, ddsc/core/userutil.py, ddsc/sdk/dukeds.py, ddsc/sdk/tests/test_dukeds.py
Before these changes DukeDSClient only allowed specifying a user by email for users already registered with DukeDS. The DukeDS API has added methods to lookup affiliates based on email address.
For all commands that receive an email address use it to try and lookup an affiliate if the user is not already registered with DukeDS. Also includes changes to try looking up a user based on their username if the specified email looks like a <username>@duke.edu email address when not found by other means.
Adds `can_deliver_to_user_with_email` and  `can_deliver_to_user_with_username` methods to the DukeDSClient `sdk` to allow users to easily check if a project can be delivered to the user associated with an email address or username.
Fixes #234
=> improve user registration via email address

ddsc/core/pathfilter.py, ddsc/core/remotestore.py, ddsc/core/tests/test_pathfilter.py, ddsc/core/tests/test_remotestore.py, ddsc/core/util.py, ddsc/tests/test_util.py
In support of #243 adds leading slash to remote paths.
This allows users to naturally specify the top level 'directory' of a remote project with '/'. 
Previously this leading slash was omitted to match the DukeDS web portal.
Changes the `download` and `deliver` commands' arguments include/exclude to allow leading slash or the current functionality of omitting the leading slash. The `list` command will now print leading slashes.
=> Add leading slash to remote paths

ddsc/cmdparser.py, ddsc/ddsclient.py, ddsc/tests/test_cmdparser.py, ddsc/tests/test_ddsclient.py
Adds `move` command to move and rename files within a DukeDS project.
CLI help for `move`:
```
usage: ddsclient move [-h] (-p ProjectName | -i ProjectUUID) Source Target
Moves and/or renames a file or folder within a project. When Target is a
directory Source will be moved into it that directory. Otherwise Source will
be renamed to the filename of Target and moved into the parent directory of
Target. Target and Source are remote paths that must start with a '/'.
positional arguments:
Source                remote path specifying the file/folder to be moved
Target                remote path specifying where to move the file/folder
to
optional arguments:
-h, --help            show this help message and exit
-p ProjectName, --project-name ProjectName
Name of the project to containing a …
```
=> Adds move command

ddsc/core/ddsapi.py, ddsc/core/tests/test_ddsapi.py
Changes logic that communicates with DukeDS API to retry a few times when a connection error occurs. There will be 5 retries after waiting a second before each retry.
This is similar to logic that already exists to [retry sending to  Swift/S3](https://github.com/Duke-GCB/DukeDSClient/blob/441a151167f6c827e824a3b546fd269e48c67f08/ddsc/core/fileuploader.py#L201-L209)
Fixes #253 
This was tested by changing `/etc/hosts` while running `ddsclient upload ...`. I was able to see the warnings and the ddsclient recover.
=> Retry DukeDS API requests for ConnectionErrors

ddsc/core/download.py, ddsc/core/tests/test_download.py, ddsc/sdk/client.py, ddsc/sdk/tests/test_client.py
Adds support to check all known hashes attached to a file when downloading. Before this change DukeDSClient only checked the first MD5 hashes found. DukeDSClient will now validate all MD5 hashes. Files that have both valid and invalid hashes will have status CONFLICTED. If there are CONFLICTED files a warning will be printed but no error raised. If there are any FAILED hashes an error will be raised.
Example terminal output after downloading a project with a conflicted file:
```
...
Verifying contents of 2 downloaded files using file hashes.
mh/me.jpeg 0106a7dcf3ab09bc47cab34a7ff1fbba md5 OK
mh/stuff.txt 7e11867261e621458a06f3e6bc301c8b md5 CONFLICTED
All downloaded files have at least one valid hash.
WARNING: Some downloaded files also have invalid hashes.
```
Example project in DukeDS …
=> Support for multiple checksums

ddsc/cmdparser.py, ddsc/core/ddsapi.py, ddsc/core/tests/test_ddsapi.py, ddsc/core/tests/test_upload.py, ddsc/core/tests/test_util.py, ddsc/core/upload.py, ddsc/core/util.py, ddsc/ddsclient.py, ddsc/sdk/client.py, ddsc/sdk/tests/test_client.py, ddsc/tests/test_cmdparser.py, ddsc/tests/test_ddsclient.py
Adds `info` command to the cli.
This command can be run like so: `ddsclient info -p <ProjectName>`.
This command prints out project Name, ID, Web Portal URL, and Size information.
Size information includes folder/file counts and total file size.
This is patterned after [project data displayed within datadelivery](https://github.com/Duke-GCB/datadelivery-ui/blob/master/app/templates/components/project-detail.hbs).
These changes may be able to simplify the [D4S2 DDSProjectSummary class](https://github.com/Duke-GCB/D4S2/blob/c8b06dfa72f0225a943f2e2c7a6e64bbc50f81a3/switchboard/dds_util.py#L206)
Supporting changes
- Moves `portal_url` method from `ddsc/core/upload.py` to `ddsc/core/ddsapi.py`.
- Moves `plural_fmt` method from `ddsc/core/upload.py` to `ddsc/core/util.py`.
- Adds …
=> add command to show project info/size

ddsc/core/d4s2.py, ddsc/core/tests/test_d4s2.py
Changes made previously require a leading slash for all DDS remote paths.
The logic that creates a file relation between copied files did not include a leading slash.
Changes here add the leading slash so the file ID can be looked up.
Fixes #269
=> fix delivery copy error

ddsc/core/d4s2.py, ddsc/core/fileuploader.py, ddsc/core/localstore.py, ddsc/core/projectuploader.py, ddsc/core/tests/test_d4s2.py, ddsc/core/tests/test_fileuploader.py, ddsc/core/tests/test_localstore.py, ddsc/core/tests/test_projectuploader.py, ddsc/core/tests/test_upload.py, ddsc/core/tests/test_util.py, ddsc/core/upload.py, ddsc/core/util.py, ddsc/ddsclient.py, ddsc/tests/test_ddsclient.py
Speeds up resuming uploads. Removes [logic that checks all hashes for existing files](https://github.com/Duke-GCB/DukeDSClient/blob/16d75079cbc28b048fdc547e928e8778190d8e9c/ddsc/core/localstore.py#L223-L231) before beginning an upload. Instead when a file is encountered that is already uploaded(hash matches) we just skip uploading it. We also sort files that are new(not present in DukeDS) so they will be processed first. This change updates the command line messaging displayed by the `upload` command to reflect these changes.
Fixes #268
=> Faster upload resume

ddsc/cmdparser.py
The `str` implementation that is part of python-future is [incompatible with urlencode](https://github.com/PythonCharmers/python-future/issues/219). This caused the KeyError when attempting to pass an email address to requests. The python-future `str` implementation is meant to be a backport of the python3 `str`.
In this PR we go back to using `unicode` and silence the bogus flake8 error `unicode` raises
Fixes #275
=> Fixes KeyError when adding user by email under python2

deploy/ddsclient-generic-gcb01.spec
Upgrades spec file to use python 3.6.
This spec file is used to add new versions of DukeDSClient to https://github.com/Duke-GCB/helmod.
=> Upgrade ddsclient environment module spec file to python3

README.md
Command examples in README were still using underscore and the client now uses dashes.
=> fix command examples to use current format

ddsc/core/download.py, ddsc/core/parallel.py, ddsc/core/projectuploader.py, ddsc/core/tests/test_download.py, ddsc/core/tests/test_parallel.py, ddsc/core/tests/test_projectuploader.py
Closes multiprocessing pool to prevent ddsclient from hanging once the download completes on Windows. This problem was not observed on Linux or Mac. This is done by simplifying the TaskRunner class to manage the executor and cleanup at the end of the run method. 
Fixes #285
=> Cleanup multiprocessing pool

ddsc/core/remotestore.py, ddsc/core/tests/test_remotestore.py
Fix patterned after https://github.com/Duke-GCB/D4S2/pull/233.
This is to work around a limitation of the DukeDS affiliate/user listing.
Fixes #290
=> derive user email when null

ddsc/core/localstore.py, ddsc/core/tests/test_localstore.py
When uploading skip non-regular files (such as pipe files, sockets, etc) and warn the user.
Fixes #288
=> Skip non-regular files when uploading

ddsc/core/fileuploader.py, ddsc/core/tests/test_fileuploader.py
Only checking size for multi-chunk uploads.
Fixes bug introduced in #293
=> Fix KeyError due to upload payload differences

ddsc/ddsclient.py, ddsc/tests/test_ddsclient.py
Show a meaningful error message if a user tries to deliver a project with the delivery recipient as a share user. Share users receive download only permission. By definition a delivery recipient must gain project admin permissions when accepting a delivery. These changes also register share users if they are not already registered with DDS.
Fixes #297 #298
=> prevent sharing with delivery recipient

deploy/ddsclient-generic-gcb01.spec
Updates to the latest python environment module for the template used when releasing new versions.
=> use Anaconda3/2019.10-gcb01 for environment module

README.md, ddsc/tests/test_versioncheck.py, integration_test.sh, setup.py
Update config and docs to require python 3.5+
python 3.4 went end of life March 18th, 2019
python 2.7 went end of life Jan 1st, 2020
=> Drop python2 support

ddsc/core/ddsapi.py, ddsc/core/tests/test_ddsapi.py, ddsc/sdk/client.py
Allow sdk users to use DDS OAuth token refreshing. Changes here add OAuthDataServiceAuth that can be programmatically used instead of DataServiceAuth. This will allow automatic token refreshing.
This is to help with https://github.com/Duke-GCB/D4S2/issues/222#issuecomment-717467907
=> Add OAuth option for DDS token creation

ddsc/config.py, ddsc/tests/test_config.py
The `yaml.safe_load` method returns None for an empty YAML file(which makes sense). 
This caused problems loading config. Changes here check for None and show a better error message.
Fixes #316
=> raise better exception for an empty config file

ddsc/__main__.py, ddsc/config.py, ddsc/core/d4s2.py, ddsc/core/ddsapi.py, ddsc/core/fileuploader.py, ddsc/core/moveutil.py, ddsc/core/remotestore.py, ddsc/core/tests/test_fileuploader.py, ddsc/core/tests/test_moveutil.py, ddsc/core/tests/test_remotestore.py, ddsc/core/tests/test_userutil.py, ddsc/core/tests/test_util.py, ddsc/core/userutil.py, ddsc/core/util.py, ddsc/ddsclient.py, ddsc/exceptions.py, ddsc/sdk/client.py, ddsc/sdk/tests/test_client.py, ddsc/tests/test_config.py, ddsc/tests/test_ddsclient.py, ddsc/tests/test_util.py, ddsc/versioncheck.py
Adds DDSUserException exception to denote exceptions containing user appropriate messages. Before this change the main function was treating all python Exceptions(non-Error) as containing user appropriate messages. For general exceptions we should fall back to the default behavior which will print a stack trace.
Fixes #318
=> Show stack traces for general exceptions

ddsc/cmdparser.py, ddsc/ddsclient.py, ddsc/tests/test_cmdparser.py, ddsc/tests/test_ddsclient.py
Adds --path option to delete command to delete a single file/folder instead of an entire project.
=> Allow deleting files/folders with ddsclient

ddsc/sdk/client.py, ddsc/sdk/tests/test_client.py, integration_test.sh
Adds missing `transferred_bytes` argument to `UploadContext.upload_file`.
Fixes #321
=> Fix DukeDS.upload_file sdk method

DukeDS/__init__.py, ddsc/cmdparser.py, ddsc/core/consistency.py, ddsc/core/ddsapi.py, ddsc/core/tests/test_consistency.py, ddsc/core/tests/test_ddsapi.py, ddsc/ddsclient.py, ddsc/sdk/client.py, ddsc/sdk/dukeds.py, ddsc/sdk/tests/test_client.py, ddsc/tests/test_cmdparser.py, ddsc/tests/test_ddsclient.py, requirements.txt, setup.py
Adds `ddsclient check -p <projectName>` command that checks that a project is in a consistent state.
There is an optional `--wait` flag for a the check command to wait until the project is consistent.
There are also sdk methods `DukeDS.is_project_consistent(projectName)` and `DukeDS.wait_for_project_consistency(projectName)`.
Fixes #324
=> Allow checking and waiting for project consistency

ddsc/core/consistency.py, ddsc/core/tests/test_consistency.py
Updates check command to handle 400 errors when checking files.
Previously we were looking for specific errors. 
Now we will also assume that the project is inconsistent if we receive any 400 errors during this process.
=> Handle 400 errors in check command

ddsc/cmdparser.py, ddsc/core/consistency.py, ddsc/core/tests/test_consistency.py, ddsc/ddsclient.py, ddsc/tests/test_cmdparser.py, ddsc/tests/test_ddsclient.py
Runs the `check --wait` logic as part of the `upload` command. 
The check can be turned off by including the `--no-check` argument.
Disables azure flag since that back end is not ready yet.
=> Check for valid download URLs after uploading
